import fs from 'node:fs/promises';
import { renderCard, escapeHtml } from '../dist/assets/catalog.mjs';
const data=JSON.parse(await fs.readFile('data/resources.json','utf8'));
const selected=data.resources.filter(r=>r.status==='selected').sort((a,b)=>a.rank-b.rank);
const candidates=data.resources.filter(r=>r.status==='candidate');
const count=kind=>selected.filter(r=>r.kinds.includes(kind)).length;
data.meta.counts=Object.fromEntries(['papers','projects','benchmarks'].map(k=>[k,count(k)]));
await fs.writeFile('data/resources.json',JSON.stringify(data,null,2)+'\n');
await fs.copyFile('data/resources.json','dist/resources.json');
let html=await fs.readFile('dist/index.html','utf8');
const content=selected.map(renderCard).join('\n');
html=html.replace(/(<div class="resource-grid" id="resources">)[\s\S]*?(<\/div>\s*<\/section>)/,`$1${content}$2`);
for(const [id,value] of [['nav-total',selected.length],['stat-papers',count('papers')],['stat-projects',count('projects')],['stat-benchmarks',count('benchmarks')]])html=html.replace(new RegExp(`(id="${id}">)[^<]*`),`$1${value}`);
html=html.replace(/(<p id="result-count"[^>]*>)[\s\S]*?<\/p>/,`$1${selected.length} 条资源 / ${selected.length} 条收录</p>`);
const about=`<div class="section-heading"><h2>有依据地收录，有边界地比较。</h2><span class="section-number">THE EDITORIAL NOTE</span></div>
<p>这是一份连接游戏与具身智能的研究资源索引。游戏方向以你提供的 Game Agent 知识库为起点，具身方向和部分游戏论文通过官方论文集、研究报告与项目仓库补充。结构参考 <a href="https://github.com/kairunwen/Awesome-Robot-Use-Agent#projects" target="_blank" rel="noopener noreferrer">Awesome-Robot-Use-Agent</a>，分类与内容独立整理。</p>
<div class="notice"><b>收录快照 · ${data.meta.snapshotDate}</b><p>共 ${selected.length} 项精选资源：${count('papers')} 篇论文、${count('projects')} 个独立项目、${count('benchmarks')} 个评测与环境。基准论文同时出现在两个视图，数量不直接相加。另有 ${candidates.length} 篇候选，不计入精选。</p></div>
<h3>01 / 收录标准</h3><div class="table-wrap"><table><thead><tr><th>类别</th><th>时间窗口</th><th>收录依据</th></tr></thead><tbody><tr><td>顶会顶刊</td><td>2021.09.14 — 2026.09.14</td><td>优先 NeurIPS、ICLR、ICML、CVPR、ICCV、ECCV、AAAI、IJCAI，以及 RSS、CoRL、ICRA、IROS 等机器人主会；期刊优先 Nature、Science、T-RO、IJRR、TPAMI、JMLR、TMLR 等。以官方发表记录核对，Workshop 单独区分。</td></tr><tr><td>重要 arXiv</td><td>2025.09.14 — 2026.09.14</td><td>以首次提交日期计算。保留系统评估、模型／环境开放等重要性理由与来源。属于编辑判断，未做引用量排名。</td></tr><tr><td>工具与环境</td><td>按当前用途核对</td><td>独立基础设施单独收录，不受论文发表窗口限制；保留接口与部署边界。</td></tr></tbody></table></div>
<p>此清单是本项目的领域选刊口径，不表示这些会议和期刊属于同一个官方等级。详见 <a href="docs/collection-policy.md" download>完整收录标准</a>。</p>
<h3>02 / 来源与核验</h3><p>本次读取论文总表 ${data.meta.sourceSnapshot.rows} 行，去除 ${data.meta.sourceSnapshot.emptyRows} 个无标题记录，并合并 ${data.meta.sourceSnapshot.duplicateRows} 个重复条目，得到 ${data.meta.sourceSnapshot.uniqueTitledRows} 条有标题的独立线索。知识库首页的历史计数未用于本版统计。</p><p>正式论文的书目信息与官方来源已核对；原知识库的核验标记保留在相关条目中。本次没有逐篇重新阅读全文，也没有独立复现实验。候选、已发表、已核验和已复现分别记录。</p><p><a href="${data.meta.knowledgeUrl}" target="_blank" rel="noopener noreferrer">源知识库（按原权限访问） ↗</a> · <a href="selection-audit.json" download>查看原始条目的筛选记录</a> · <a href="resources.json" download>下载资源数据 JSON</a></p>
<h3>03 / 两个方向如何比较</h3><div class="table-wrap"><table><thead><tr><th>维度</th><th>游戏研究</th><th>具身研究</th></tr></thead><tbody><tr><td>环境与任务</td><td>游戏、地图、模式、任务范围</td><td>硬件、场景、物体、操作任务</td></tr><tr><td>观察权限</td><td>像素、声音、文本、引擎状态</td><td>图像、深度、触觉、本体信息</td></tr><tr><td>动作层级</td><td>键鼠、程序 API、预定义技能</td><td>关节、末端位姿、导航或操作技能</td></tr><tr><td>数据与学习</td><td>玩家轨迹、在线交互、视频预训练</td><td>示范、遥操作、仿真与真实交互</td></tr><tr><td>执行约束</td><td>决策时延、帧率、是否暂停</td><td>控制频率、碰撞、硬件限制</td></tr><tr><td>评测证据</td><td>地图划分、任务指标、样本与种子</td><td>任务成功率、泛化、人工干预</td></tr></tbody></table></div>
<p>共享方法并不意味着能力已经跨域迁移。画面生成、游戏导航、机器人规划与物理执行，应当各自保留证据边界。</p>
<h3>04 / 持续维护</h3><p>README 和网站使用同一份资源数据。此版本是人工整理快照；新增论文需按收录标准补充来源后更新。查看 <a href="CONTRIBUTING.md" download>贡献指南</a> 或 <a href="README.md" download>项目文档</a>。</p>`;
html=html.replace(/(<section id="about" class="about-panel" hidden>)[\s\S]*?<\/section>/,`$1${about}</section>`);
await fs.writeFile('dist/index.html',html);
const md=s=>String(s||'—').replace(/\|/g,'／').replace(/\n/g,' ');
const link=(url,text)=>url?`[${text}](${url})`:'';
const links=r=>Object.entries(r.links).map(([k,v])=>link(v,{paper:'Paper',code:'Code',project:'Project'}[k]||k)).join(' · ');
const paperRows=items=>items.map(r=>`| **${link(r.links.paper,r.name)}**<br>${md(r.title)} | ${md(r.venue)} | ${md(r.summary)} | ${links(r)} |`).join('\n');
const projectRows=items=>items.map(r=>`| **${r.name}** | ${md(r.environment)} | ${md(r.interface)} | ${md(r.limits)} | ${links(r)} |`).join('\n');
let readme=`# Awesome Game & Embodied Agents\n\n游戏与具身智能研究资源集：从感知、规划和记忆，到游戏动作与机器人控制。\n\n**${count('papers')} 篇精选论文 · ${count('projects')} 个独立开源项目 · ${count('benchmarks')} 个评测／环境 · ${candidates.length} 篇候选**\n\n快照：${data.meta.snapshotDate}。具有论文的基准共享同一条记录，视图计数存在重叠；精选资源总数为 ${selected.length}。\n\n本项目基于用户提供的 [Game Agent 知识库](${data.meta.knowledgeUrl})，参考 [Awesome-Robot-Use-Agent](${data.meta.referenceUrl}) 的资源组织方式；具身与部分游戏内容从官方来源补充。\n\n[精选论文](#papers) · [开源项目](#projects) · [评测环境](#benchmarks) · [候选论文](#candidates) · [收录标准](docs/collection-policy.md) · [贡献指南](CONTRIBUTING.md)\n\n## 收录范围\n\n- 正式论文：2021-09-14 至 2026-09-14 的相关顶会顶刊，官方发表记录可追溯。\n- 重要 arXiv：首次提交于 2025-09-14 至 2026-09-14，附重要性判断和研究证据，未确认正式接收时明确标注预印本。\n- 未充分核对的条目独立列为候选；基础设施按用途收录，不受论文年限限制。\n- 不声称穷尽检索、统一排名或已独立复现；元数据核对不等于阅读全文。\n\n## Papers\n\n### Game Agents\n\n| Paper | Venue | Research focus | Sources |\n| --- | --- | --- | --- |\n${paperRows(selected.filter(r=>r.kinds.includes('papers')&&r.domains.includes('game')))}\n\n### Embodied Agents\n\n跨域论文在两个方向均显示，但数据中只有一个条目。会议年与论文集出版年不同时，以会议年展示，并在数据的 publicationNote 中注明。\n\n| Paper | Venue | Research focus | Sources |\n| --- | --- | --- | --- |\n${paperRows(selected.filter(r=>r.kinds.includes('papers')&&r.domains.includes('embodied')))}\n\n## Projects\n\n独立工具、框架与基础设施。论文配套代码随论文列出。\n\n| Project | Environment / role | Interface | Setup & limits | Official sources |\n| --- | --- | --- | --- | --- |\n${projectRows(selected.filter(r=>r.kinds.includes('projects')))}\n\n## Benchmarks\n\n同一基准若有正式论文，保留论文与环境两种视图。使用时需记录版本、动作空间、观测权限和任务子集。\n\n| Benchmark / environment | Environment / task | Interface | Evaluation boundary | Sources |\n| --- | --- | --- | --- | --- |\n${projectRows(selected.filter(r=>r.kinds.includes('benchmarks')))}\n\n## Candidates\n\n以下是知识库中的近一年线索，影响力或正式发表证据尚待充分核验，不计入精选。\n\n| Paper | Recorded year | Pending review | Source |\n| --- | --- | --- | --- |\n${candidates.map(r=>`| ${md(r.title)} | ${r.year} | ${md(r.selectionReason)} | ${links(r)} |`).join('\n')}\n\n## 来源与筛选记录\n\n本次论文总表读取 ${data.meta.sourceSnapshot.rows} 行，${data.meta.sourceSnapshot.emptyRows} 行无标题，合并 ${data.meta.sourceSnapshot.duplicateRows} 行重复，得到 ${data.meta.sourceSnapshot.uniqueTitledRows} 条独立有标题线索。未入选不代表质量判断；具体处理见 [筛选记录](data/selection-audit.json)。\n\n每个条目保留来源、核对日期、环境、接口、比较边界与收录依据；保留的知识库原核验声明不视作本次重新核验。原始导出位于被忽略的本地目录，不包含于发布内容。未同步修改原飞书知识库。\n\n## Website\n\n无需第三方前端依赖。Node.js 20+：\n\n\`\`\`sh\nnpm run build\nnpm run check\nnpm run dev\n\`\`\`\n\n打开终端打印的本地网址。网页支持领域、类型、主题、年份、关键词筛选，以及可分享的 URL 筛选状态。静态 HTML 自带完整精选列表，交互数据加载失败时仍可阅读。\n\n- 内容入口：\`data/resources.json\`。\n- 网站输出：\`dist/\`，可部署到任意静态托管。\n- 生成步骤会同步 README、静态页面和网站数据；不要直接修改生成的列表。\n- 网站通过 GitHub Pages 发布。仓库 Settings → Pages 中的发布来源选择 GitHub Actions。\n- 更新并推送到 \`main\` 后自动检查、构建和发布；也可在 Actions → Publish GitHub Pages 中手动运行。\n- 新部署状态可在仓库 Actions 查看；复制仓库时请同步修改 \`data/resources.json\` 中的网站和仓库地址。\n\n## License & attribution\n\n原始网站代码采用 [MIT](LICENSE)。引用论文、第三方代码、模型、数据和知识库内容保留各自权利。此索引不重新授权被引用作品。\n`;
readme=readme.replace('## Website', `## Website\n\n[展示网站](${data.meta.siteUrl}) · [GitHub 项目](${data.meta.repositoryUrl})\n\n展示网站由 GitHub Pages 托管，网页公开访问。`);
await fs.writeFile('README.md',readme);
await fs.mkdir('dist/docs',{recursive:true});
for(const f of ['README.md','CONTRIBUTING.md','LICENSE'])await fs.copyFile(f,'dist/'+f);
await fs.copyFile('docs/collection-policy.md','dist/docs/collection-policy.md');
await fs.copyFile('data/selection-audit.json','dist/selection-audit.json');
console.log(`Built ${selected.length} selected resources and ${candidates.length} candidates.`);
